name: Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore "Genshin Stella Mod Pack made by Sefinek.sln"

      - name: Build Solution
        run: |
          msbuild.exe Genshin Stella Mod Pack made by Sefinek.sln" /p:platform="Any CPU" /p:configuration="Release"
