name: Build Stella Mod Launcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet Packages for Stella Mod Launcher
        run: msbuild -t:restore "Stella Mod Launcher\1. Stella Mod Launcher.csproj"

      - name: Build Stella Mod Launcher
        run: msbuild "Stella Mod Launcher\1. Stella Mod Launcher.csproj" -p:Configuration=Release -p:Platform="Any CPU"

      - name: Run Stella Mod Launcher
        run: .\Build\Release\Stella Mod Launcher.exe
